-- =============================================================================
-- Dummy catalog data for local UI testing — 10 books, 3 authors, 2 publishers.
-- Distinct, hand-written content per book (not repeated placeholder text) so
-- descriptions/summaries/key takeaways/related-books all look realistic.
--
-- LOCAL ONLY. This is fake data for local dev — never run with --remote.
-- Production already has its own real catalog (~thousands of rows); running
-- this against production would pollute it with test books.
--
-- Run AFTER catalog_schema.sql:
--   npx wrangler d1 execute catalog --local --file=sql/catalog_schema.sql
--   npx wrangler d1 execute catalog --local --file=sql/catalog_seed.sql
-- =============================================================================

DELETE FROM books;
INSERT INTO books (slug, lang, title, author, publisher, isbn, published, page_count, format, description, summary, category, collection, genres, subjects, tags, key_points, rating, cover_url, country, featured, bestseller) VALUES ('dummy-book-one-000001', 'en', 'The Silent Orchard', 'Jane Writer', 'Dummy Press', '9780000000001', '2020', 280, 'Paperback', 'A family returns to their childhood orchard after decades away, only to find its quiet rows hiding secrets that reshape everything they believed about their parents'' marriage.', 'Three siblings reunite at their late father''s failing orchard and, over one long harvest season, uncover a hidden correspondence that reveals why their mother left without explanation twenty years earlier.', 'Fiction', 'Test Collection', '["Fiction", "Family Drama"]', '["Family relationships", "Grief", "Rural life"]', '["test", "dummy"]', '["A story about inherited silence and what it costs a family", "Explores how grief can masquerade as anger across generations", "The orchard itself becomes a character, marking time through each harvest"]', 4.5, 'https://covers.openlibrary.org/b/id/1-M.jpg', 'United States', 1, 1);
INSERT INTO books (slug, lang, title, author, publisher, isbn, published, page_count, format, description, summary, category, collection, genres, subjects, tags, key_points, rating, cover_url, country, featured, bestseller) VALUES ('dummy-book-two-000002', 'en', 'Thinking in Systems, Badly', 'John Author', 'Sample Books Co', '9780000000002', '2019', 320, 'Hardcover', 'A practical, occasionally irreverent guide to why well-intentioned organizations keep producing the outcomes they''re explicitly trying to avoid.', 'Drawing on failures from software teams to city planning departments, this book argues that most organizational dysfunction isn''t a people problem — it''s a feedback-loop problem, and shows readers how to spot the loops working against them.', 'Non-Fiction', 'Test Collection', '["Business", "Systems Thinking"]', '["Organizational behavior", "Decision making", "Management"]', '["test", "dummy"]', '["Most \"people problems\" are actually badly designed feedback loops", "A checklist for auditing incentive structures before blaming individuals", "Case studies spanning startups, hospitals, and municipal governments"]', 4.2, 'https://covers.openlibrary.org/b/id/2-M.jpg', 'United Kingdom', 0, 1);
INSERT INTO books (slug, lang, title, author, publisher, isbn, published, page_count, format, description, summary, category, collection, genres, subjects, tags, key_points, rating, cover_url, country, featured, bestseller) VALUES ('dummy-book-three-000003', 'en', 'The Cartographer''s Debt', 'Maria Scribe', 'Dummy Press', '9780000000003', '2021', 400, 'EBook', 'In a city where maps are currency and borders shift overnight, an apprentice cartographer inherits a debt she never agreed to — payable only in truths she isn''t ready to draw.', 'Kes has spent her life learning to render her city faithfully, until she discovers her late mentor sold a map that doesn''t exist to a buyer who now wants it drawn into being — even if that means redrawing reality itself.', 'Fantasy', 'Test Collection', '["Fantasy", "Coming of Age"]', '["Magic systems", "Found family", "Debt and obligation"]', '["test", "dummy"]', '["A magic system built entirely around cartography and consequence", "Kes must choose between the map that is true and the one that is owed", "A slow-burn mystery about what her mentor was really running from"]', 4.8, 'https://covers.openlibrary.org/b/id/3-M.jpg', 'Canada', 1, 0);
INSERT INTO books (slug, lang, title, author, publisher, isbn, published, page_count, format, description, summary, category, collection, genres, subjects, tags, key_points, rating, cover_url, country, featured, bestseller) VALUES ('dummy-book-four-000004', 'en', 'Small Hours', 'Jane Writer', 'Sample Books Co', '9780000000004', '2018', 210, 'Paperback', 'A collection of linked short stories following the overnight shift at a hospital''s emergency room, told from the perspective of everyone except the doctors.', 'From the janitor who has memorized every patient''s footsteps to the vending machine repairman who knows more secrets than the chaplain, this collection captures a single hospital across one unbearably long night.', 'Fiction', 'Test Collection', '["Fiction", "Short Stories"]', '["Working class life", "Hospitals", "Ensemble narrative"]', '["test", "dummy"]', '["Nine interconnected stories set during one overnight shift", "Centers the hospital''s invisible workers rather than its doctors", "A quiet meditation on who gets to be the hero of a crisis"]', 3.9, 'https://covers.openlibrary.org/b/id/4-M.jpg', 'United States', 0, 0);
INSERT INTO books (slug, lang, title, author, publisher, isbn, published, page_count, format, description, summary, category, collection, genres, subjects, tags, key_points, rating, cover_url, country, featured, bestseller) VALUES ('dummy-book-five-000005', 'en', 'The Founder''s Fallacy', 'John Author', 'Dummy Press', '9780000000005', '2022', 350, 'Hardcover', 'A contrarian look at startup mythology, arguing that most of the traits we celebrate in successful founders are survivorship bias dressed up as strategy.', 'Using interviews with founders who failed for the exact same reasons others succeeded, this book dismantles the idea that conviction, speed, and risk tolerance reliably predict outcomes — and offers a more honest framework for evaluating your own odds.', 'Non-Fiction', 'Test Collection', '["Business", "Entrepreneurship"]', '["Startups", "Survivorship bias", "Risk"]', '["test", "dummy"]', '["Most founder advice is survivorship bias retold as wisdom", "A framework for separating signal from noise in your own decisions", "Interviews with founders who did everything \"right\" and still failed"]', 4.0, 'https://covers.openlibrary.org/b/id/5-M.jpg', 'United Kingdom', 0, 0);
INSERT INTO books (slug, lang, title, author, publisher, isbn, published, page_count, format, description, summary, category, collection, genres, subjects, tags, key_points, rating, cover_url, country, featured, bestseller) VALUES ('dummy-book-six-000006', 'en', 'The Weight of Water Lilies', 'Maria Scribe', 'Sample Books Co', '9780000000006', '2017', 290, 'Paperback', 'A reclusive painter is commissioned to restore a mural in a drowned village''s only surviving building, and finds the water has preserved more than just the walls.', 'When the reservoir that swallowed her grandmother''s village drops to its lowest level in fifty years, Odalys is hired to document the exposed ruins — and begins seeing figures in the mural that shouldn''t still be moving.', 'Fantasy', 'Test Collection', '["Fantasy", "Magical Realism"]', '["Memory", "Drowned villages", "Inherited trauma"]', '["test", "dummy"]', '["A magical realist meditation on what floods take and what they preserve", "Odalys must reconcile her grandmother''s stories with what she finds", "The mural itself functions as a slowly-revealed second narrative"]', 4.6, 'https://covers.openlibrary.org/b/id/6-M.jpg', 'Canada', 1, 1);
INSERT INTO books (slug, lang, title, author, publisher, isbn, published, page_count, format, description, summary, category, collection, genres, subjects, tags, key_points, rating, cover_url, country, featured, bestseller) VALUES ('dummy-book-seven-000007', 'en', 'Nobody Reads the Manual', 'Jane Writer', 'Dummy Press', '9780000000007', '2023', 260, 'EBook', 'A field guide to designing products, policies, and processes for how people actually behave — not how we wish they would.', 'Drawing on failed onboarding flows, ignored safety warnings, and abandoned government forms, this book makes the case that most usability failures aren''t user error — they''re designer optimism.', 'Fiction', 'Test Collection', '["Fiction", "Satire"]', '["Design", "User behavior", "Bureaucracy"]', '["test", "dummy"]', '["A satirical tour of forms, warnings, and flows nobody follows", "Argues that \"user error\" is usually a design confession", "Short, standalone chapters built around real failed designs"]', 3.7, 'https://covers.openlibrary.org/b/id/7-M.jpg', 'United States', 0, 0);
INSERT INTO books (slug, lang, title, author, publisher, isbn, published, page_count, format, description, summary, category, collection, genres, subjects, tags, key_points, rating, cover_url, country, featured, bestseller) VALUES ('dummy-book-eight-000008', 'en', 'The Quiet Ledger', 'John Author', 'Sample Books Co', '9780000000008', '2016', 330, 'Paperback', 'A forensic accountant investigating a small-town co-op''s missing funds discovers the fraud is smaller than the silence protecting it.', 'Every number in the co-op''s books balances perfectly — which is exactly what tips off Priya that someone has spent thirty years making sure they would. What she uncovers implicates half the town in a debt none of them will name.', 'Non-Fiction', 'Test Collection', '["Mystery", "True Crime"]', '["Small towns", "Financial fraud", "Community secrets"]', '["test", "dummy"]', '["A slow-burn financial mystery where the numbers are the least of it", "Priya must decide whether exposing the truth helps anyone", "Grounded in how real small-town fraud investigations actually unfold"]', 4.1, 'https://covers.openlibrary.org/b/id/8-M.jpg', 'United Kingdom', 0, 0);
INSERT INTO books (slug, lang, title, author, publisher, isbn, published, page_count, format, description, summary, category, collection, genres, subjects, tags, key_points, rating, cover_url, country, featured, bestseller) VALUES ('dummy-book-nine-000009', 'en', 'Everything We Buried in the Garden', 'Maria Scribe', 'Dummy Press', '9780000000009', '2024', 300, 'Hardcover', 'Three generations of women tend the same garden across sixty years, each burying something they couldn''t say out loud — until a new owner starts digging.', 'When Yuki inherits her great-grandmother''s house, she starts a garden of her own — and keeps unearthing objects that don''t belong to any story she''s been told, forcing three generations of family silence into the open at once.', 'Fantasy', 'Test Collection', '["Fiction", "Family Saga"]', '["Multi-generational stories", "Family secrets", "Gardens"]', '["test", "dummy"]', '["Told across three timelines, one per generation of women", "The garden itself is the only witness to everything buried", "A gentle unraveling rather than a dramatic reveal"]', 4.9, 'https://covers.openlibrary.org/b/id/9-M.jpg', 'Canada', 1, 1);
INSERT INTO books (slug, lang, title, author, publisher, isbn, published, page_count, format, description, summary, category, collection, genres, subjects, tags, key_points, rating, cover_url, country, featured, bestseller) VALUES ('dummy-book-ten-000010', 'en', 'The Understudy Economy', 'Jane Writer', 'Sample Books Co', '9780000000010', '2015', 240, 'Paperback', 'An investigation into the invisible labor of "backup" workers — the substitutes, understudies, and on-call staff an entire economy quietly depends on.', 'From Broadway understudies who''ve never gone on stage to gig workers who exist purely as scheduling insurance, this book profiles the people whose entire job is being ready for a call that might never come.', 'Fiction', 'Test Collection', '["Non-Fiction", "Labor"]', '["Gig economy", "Invisible labor", "Work culture"]', '["test", "dummy"]', '["Profiles workers whose job is readiness, not output", "Examines what \"backup\" labor reveals about how we value work", "Ends with a proposal for compensating standby time fairly"]', 3.5, 'https://covers.openlibrary.org/b/id/10-M.jpg', 'United States', 0, 0);
DELETE FROM authors;
INSERT INTO authors (slug, lang, name, birth_year, country, bio, famous_work, genres, image_url, wikipedia_url, website_url, verified) VALUES ('jane-writer', 'en', 'Jane Writer', 1978, 'United States', 'Jane Writer spent a decade as a hospice volunteer before turning to fiction, and it shows — her novels linger in quiet rooms and unfinished conversations rather than dramatic turns. She lives outside Portland with two dogs and a much-abused writing shed.', 'The Silent Orchard', '["Fiction", "Family Drama", "Short Stories"]', 'https://i.pravatar.cc/300?u=jane-writer', 'https://en.wikipedia.org/wiki/Jane_Writer', 'https://example.com/jane-writer', 1);
INSERT INTO authors (slug, lang, name, birth_year, country, bio, famous_work, genres, image_url, wikipedia_url, website_url, verified) VALUES ('john-author', 'en', 'John Author', 1971, 'United Kingdom', 'A former management consultant who grew tired of watching the same organizational mistakes repeat under new names, John Author now writes about why systems fail the people who design them. His talks have been mistaken for stand-up comedy more than once.', 'Thinking in Systems, Badly', '["Business", "Systems Thinking", "Entrepreneurship"]', 'https://i.pravatar.cc/300?u=john-author', 'https://en.wikipedia.org/wiki/John_Author', NULL, 0);
INSERT INTO authors (slug, lang, name, birth_year, country, bio, famous_work, genres, image_url, wikipedia_url, website_url, verified) VALUES ('maria-scribe', 'en', 'Maria Scribe', 1985, 'Canada', 'Maria Scribe grew up in a family of cartographers and mapmakers, which she blames entirely for her fascination with places that don''t officially exist. Her novels blend fantasy with the very real geography of the towns she''s lived in.', 'The Cartographer''s Debt', '["Fantasy", "Magical Realism", "Coming of Age"]', 'https://i.pravatar.cc/300?u=maria-scribe', NULL, 'https://example.com/maria-scribe', 1);
INSERT INTO authors (slug, lang, name, birth_year, country, bio, famous_work, genres, image_url, wikipedia_url, website_url, verified) VALUES ('devika-rao', 'en', 'Devika Rao', 1990, 'India', 'Devika Rao writes speculative fiction rooted in the coastal towns of her childhood, weaving folklore with questions about climate and displacement. Her debut collection was translated into six languages within its first year.', 'The Tide Remembers', '["Fiction", "Speculative Fiction", "Short Stories"]', 'https://i.pravatar.cc/300?u=devika-rao', 'https://en.wikipedia.org/wiki/Devika_Rao', 'https://example.com/devika-rao', 1);
INSERT INTO authors (slug, lang, name, birth_year, country, bio, famous_work, genres, image_url, wikipedia_url, website_url, verified) VALUES ('marcus-webb', 'en', 'Marcus Webb', 1965, 'Australia', 'Marcus Webb spent twenty years as a field biologist before his first book, and his writing still carries a scientist''s patience for small, careful observation. He now splits his time between Tasmania and wherever the research takes him.', 'Notes from the Understory', '["Non-Fiction", "Nature Writing", "Science"]', 'https://i.pravatar.cc/300?u=marcus-webb', NULL, 'https://example.com/marcus-webb', 0);
INSERT INTO authors (slug, lang, name, birth_year, country, bio, famous_work, genres, image_url, wikipedia_url, website_url, verified) VALUES ('amara-nwosu', 'en', 'Amara Nwosu', 1988, 'Nigeria', 'Amara Nwosu writes about ambition, migration, and the families left to make sense of both. A former corporate lawyer, she brings a forensic eye to the quiet betrayals that hold her novels together.', 'The Inheritance We Chose', '["Fiction", "Family Drama", "Literary Fiction"]', 'https://i.pravatar.cc/300?u=amara-nwosu', 'https://en.wikipedia.org/wiki/Amara_Nwosu', NULL, 1);
INSERT INTO authors (slug, lang, name, birth_year, country, bio, famous_work, genres, image_url, wikipedia_url, website_url, verified) VALUES ('tomas-lindqvist', 'en', 'Tomas Lindqvist', 1958, 'Sweden', 'Tomas Lindqvist has spent four decades writing crime fiction set in the small fishing towns north of Stockholm, where he insists the real mysteries are far stranger than anything he''s invented. His long-running detective series has never once left Sweden.', 'The Herring Gull Murders', '["Mystery", "True Crime", "Fiction"]', 'https://i.pravatar.cc/300?u=tomas-lindqvist', 'https://en.wikipedia.org/wiki/Tomas_Lindqvist', 'https://example.com/tomas-lindqvist', 0);
DELETE FROM catalog_counts WHERE id=1;
INSERT INTO catalog_counts (id, books, authors, publications) VALUES (1, 10, 8, 2);
